/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef mozilla_dom_InspectorUtilsBinding_h__
#define mozilla_dom_InspectorUtilsBinding_h__

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/DOMJSClass.h"
#include "mozilla/dom/DOMJSProxyHandler.h"

class XPCWrappedNativeScope;

namespace mozilla {
namespace dom {

struct InspectorRGBTriple : public MainThreadDictionaryBase {
  InspectorRGBTriple() {}
  bool Init(JSContext* cx, JSObject* scopeObj, const JS::Value& val);
  bool ToObject(JSContext* cx, JSObject* parentObject, JS::Value *vp);

  bool Init(const nsAString& aJSON)
  {
    mozilla::Maybe<JSAutoRequest> ar;
    mozilla::Maybe<JSAutoCompartment> ac;
    jsval json = JSVAL_VOID;
    JSContext* cx = ParseJSON(aJSON, ar, ac, json);
    NS_ENSURE_TRUE(cx, false);
    return Init(cx, nullptr, json);
  }
  InspectorRGBTriple& AsMutable() const
  {
    return *const_cast<InspectorRGBTriple*>(this);
  }

  uint8_t mB;
  uint8_t mG;
  uint8_t mR;
private:
  // Disallow copy-construction
  InspectorRGBTriple(const InspectorRGBTriple&) MOZ_DELETE;
  static bool InitIds(JSContext* cx);
  static bool initedIds;
  static jsid b_id;
  static jsid g_id;
  static jsid r_id;
};
struct InspectorRGBTripleInitializer : public InspectorRGBTriple {
  InspectorRGBTripleInitializer() {
    // Safe to pass a null context if we pass a null value
    Init(nullptr, nullptr, JS::NullValue());
  }
};

} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_InspectorUtilsBinding_h__
