/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef mozilla_dom_PannerNodeBinding_h__
#define mozilla_dom_PannerNodeBinding_h__

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/DOMJSClass.h"
#include "mozilla/dom/DOMJSProxyHandler.h"

class XPCWrappedNativeScope;
namespace mozilla {
namespace dom {

class PannerNode;

} // namespace dom
} // namespace mozilla


namespace mozilla {
namespace dom {

template <>
struct PrototypeTraits<prototypes::id::PannerNode>
{
  enum
  {
    Depth = 1
  };
  typedef mozilla::dom::PannerNode NativeType;
};
template <>
struct PrototypeIDMap<mozilla::dom::PannerNode>
{
  enum
  {
    PrototypeID = prototypes::id::PannerNode
  };
};
} // namespace dom
} // namespace mozilla


namespace mozilla {
namespace dom {

namespace PanningModelTypeValues {

  enum valuelist {
    Equalpower,
    HRTF,
    Soundfield
  };

  extern const EnumEntry strings[4];
} // namespace PanningModelTypeValues


typedef PanningModelTypeValues::valuelist PanningModelType;


namespace DistanceModelTypeValues {

  enum valuelist {
    Linear,
    Inverse,
    Exponential
  };

  extern const EnumEntry strings[4];
} // namespace DistanceModelTypeValues


typedef DistanceModelTypeValues::valuelist DistanceModelType;


namespace PannerNodeBinding {

  extern const NativePropertyHooks sNativePropertyHooks;

  void
  CreateInterfaceObjects(JSContext* aCx, JSObject* aGlobal, JSObject** protoAndIfaceArray);

  inline JSObject* GetProtoObject(JSContext* aCx, JSObject* aGlobal)
  {

    /* Get the interface prototype object for this class.  This will create the
       object as needed. */

    /* Make sure our global is sane.  Hopefully we can remove this sometime */
    if (!(js::GetObjectClass(aGlobal)->flags & JSCLASS_DOM_GLOBAL)) {
      return NULL;
    }
    /* Check to see whether the interface objects are already installed */
    JSObject** protoAndIfaceArray = GetProtoAndIfaceArray(aGlobal);
    JSObject* cachedObject = protoAndIfaceArray[prototypes::id::PannerNode];
    if (!cachedObject) {
      CreateInterfaceObjects(aCx, aGlobal, protoAndIfaceArray);
      cachedObject = protoAndIfaceArray[prototypes::id::PannerNode];
    }

    /* cachedObject might _still_ be null, but that's OK */
    return cachedObject;
  }

  inline JSObject* GetConstructorObject(JSContext* aCx, JSObject* aGlobal)
  {

    /* Get the interface object for this class.  This will create the object as
       needed. */

    /* Make sure our global is sane.  Hopefully we can remove this sometime */
    if (!(js::GetObjectClass(aGlobal)->flags & JSCLASS_DOM_GLOBAL)) {
      return NULL;
    }
    /* Check to see whether the interface objects are already installed */
    JSObject** protoAndIfaceArray = GetProtoAndIfaceArray(aGlobal);
    JSObject* cachedObject = protoAndIfaceArray[constructors::id::PannerNode];
    if (!cachedObject) {
      CreateInterfaceObjects(aCx, aGlobal, protoAndIfaceArray);
      cachedObject = protoAndIfaceArray[constructors::id::PannerNode];
    }

    /* cachedObject might _still_ be null, but that's OK */
    return cachedObject;
  }

  JSObject*
  DefineDOMInterface(JSContext* aCx, JSObject* aGlobal, jsid id, bool* aEnabled);

  bool
  PrefEnabled();

  extern DOMJSClass Class;

  JSObject*
  Wrap(JSContext* aCx, JSObject* aScope, mozilla::dom::PannerNode* aObject);

} // namespace PannerNodeBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_PannerNodeBinding_h__
