/*
  Free Download Manager Copyright (c) 2003-2014 FreeDownloadManager.ORG
*/

//{{NO_DEPENDENCIES}}

#define IDOK2                           3
#define IDC_ADVANCED                    3
#define IDC_ENTERCODE                   3
#define IDC_SETSOUND                    3
#define IDC_VISITWEBSITE                3
#define IDC_PASTEFROMCLIPBOARD          3
#define IDC_ABORT                       3
#define IDC_ORDER2                      4
#define IDC_REMOVE                      4
#define IDC_MIRRORS                     4
#define IDC_BTN2                        4
#define IDC_TEST                        5
#define IDC_MALICIOUS                   5
#define IDC_BTN1                        5
#define IDC_ADD                         6
#define IDC_BTN3                        6
#define IDD_ABOUTBOX                    100
#define IDR_FDMAPP                      102
#define IDR_WGURLRECEIVER               103
#define IDR_WGURLLISTRECEIVER           104
#define IDR_FDMDOWNLOADSSTAT            106
#define IDR_FDMDOWNLOAD                 107
#define IDR_FDMUPLOADER                 108
#define IDR_FDMUPLOADPACKAGE            109
#define IDR_FDMTORRENTFILESRCVR         110
#define IDR_FDMFLASHVIDEODOWNLOADS      111
#define IDR_FDM                         112
#define IDR_FDMFLVDOWNLOAD              113
#define IDD_IWMANAGERSPROPERTYPAGE      114
#define IDD_IWPROGRESSPROPERTYPAGE      115
#define IDD_IWRESULTPROPERTYPAGE        116
#define IDR_MAINFRAME                   128
#define IDR_DATASTTYPE                  129
#define IDD_ENTERURL                    130
#define IDM_DOWNLOADS                   133
#define IDB_DOWNLOADSINFO               134
#define IDB_DOWNLOADSTASKS              135
#define IDD_CREATEDOWNLOAD              136
#define IDB_GROUPS                      137
#define IDD_DOWNLOAD_INFO               138
#define IDD_DOWNLOAD_GENERAL            138
#define IDD_DIALOG1                     139
#define IDD_MSG                         139
#define IDD_WAITER                      140
#define IDB_LOGSTATES                   141
#define IDM_GROUP                       142
#define IDB_MENU                        143
#define IDD_DLDGROUP                    144
#define IDD_DOWNLOAD_PROXY              146
#define IDD_DIALOG3                     147
#define IDD_DOWNLOAD_PROTOCOL           148
#define IDD_DOWNLOAD_CONNECTION         149
#define IDD_DOWNLOAD_MISC               152
#define IDM_LOG                         153
#define IDD_DLDR_LIST                   155
#define IDD_OPTMASTER                   156
#define IDM_TASKS                       157
#define IDB_SHEDULER                    158
#define IDD_SCHEDULE_WHATTOSTART        159
#define IDD_SCHEDULE_WHENTOSTART        160
#define IDI_CHOOSEFOLDER                162
#define IDI_CREATEGROUP                 164
#define IDI_TOSEL                       165
#define IDI_TOUNSEL                     166
#define IDD_DIAL                        167
#define IDI_SETTIME                     168
#define IDD_SCHEDULE_ADVANCED           169
#define IDD_WAITFORCONFIRMATION         170
#define IDI_TRAY                        171
#define IDI_TRAY_NORMAL                 171
#define IDM_TRAY                        172
#define IDM_HFE                         173
#define IDB_FILELIST                    174
#define IDI_GO                          175
#define IDD_AER                         176
#define IDD_SCR                         177
#define IDD_DDR                         178
#define IDD_REQLOGIN                    179
#define IDI_LOGIN                       180
#define IDD_CREATEDOWNLOADS             181
#define IDB_CHECKS                      182
#define IDD_HFE_PROTOCOL                183
#define IDB_TOOL0                       184
#define IDB_TOOL_DLDS                   185
#define IDB_TOOL_SCHEDULE               186
#define IDB_TOOL_HFE                    187
#define IDI_TRAY_DOWNLOADING            188
#define IDI_TRAY_ERRORS                 189
#define IDD_DLDR_MONITOR                190
#define IDB_GROUPSMENU                  191
#define IDD_PRG_GENERAL                 192
#define IDD_PRG_UPDATE                  193
#define IDC_HAND_                       195
#define IDD_UPDATE                      196
#define IDM_WT                          197
#define IDD_NAGSCREEN                   198
#define IDD_ENTERKEY                    199
#define IDB_TOOL0_D                     200
#define IDB_TOOL_DLDS_D                 201
#define IDB_TOOL_HFE_D                  202
#define IDB_TOOL_SCHEDULE_D             203
#define IDB_GROUPSMENU_D                204
#define IDD_BUY                         205
#define IDM_SITES                       206
#define IDB_TOOL_SITES                  207
#define IDB_TOOL_SITES_D                208
#define IDB_SITELIST                    209
#define IDD_SITES_GENERAL               210
#define IDR_SPIDER                      211
#define IDM_SPIDER                      211
#define IDB_TOOL_SPIDER                 212
#define IDB_TOOL_SPIDER_D               213
#define IDD_SPIDER_ADD                  214
#define IDD_WPD_GENERAL                 215
#define IDD_WPDS_GENERAL                215
#define IDD_WPD_WEBPAGES                216
#define IDD_WPDS_WEBPAGES               216
#define IDD_WPD_IMAGES                  217
#define IDD_WPD_FILES                   218
#define IDD_WPDS_FILES                  218
#define IDD_WPDS_IMAGES                 219
#define IDM_SPIDER_TREE                 220
#define IDD_SITES_ADVANCED              221
#define IDB_GO                          222
#define IDB_DOWNLOADSTASKS_SEL          223
#define IDB_SCHEDULER_SEL               227
#define IDB_FILELIST_SEL                228
#define IDB_SITELIST_SEL                229
#define IDM_DL_VIEW                     230
#define IDM_HFE_VIEW                    231
#define IDM_TASKS_VIEW                  232
#define IDM_SITES_VIEW                  233
#define IDM_SPIDER_VIEW                 234
#define IDI_TRAY_UNKNOWN                236
#define IDD_CREATEBATCHDOWNLOAD         237
#define IDD_CBD_RESULTS                 238
#define IDB_BACK                        239
#define IDB_BACK_D                      240
#define IDB_SORTIMAGES                  241
#define IDD_UNHEXC                      242
#define IDD_DLDALREXISTS                243
#define IDD_ADDURLLIST                  244
#define IDD_CREATEURLLIST               244
#define IDD_DLDR_NOTIFICATIONS          245
#define IDD_DLDR_MIRRORS                246
#define IDD_DOWNLOAD_MIRRORS            247
#define IDD_URLWITHLOGIN                248
#define IDD_DLDR_DEFDLD                 249
#define IDD_DLDR_NEWDLD                 249
#define IDD_CUSTOMIZEIEMENU             250
#define IDD_SOUNDS                      251
#define IDD_PRG_HISTORY                 252
#define IDD_EXPDLDS                     253
#define IDD_DELETED_PROPS               254
#define IDM_DELETEDITEMS                255
#define IDD_DOWNLOADSHISTORY_SETTINGS   256
#define IDD_T1TOT2                      257
#define IDD_FIND                        258
#define IDD_FIND_ADVANCED               259
#define IDM_HISTORYITEMS                260
#define IDD_ZIPPREVIEW                  261
#define IDD_VIDMAN                      262
#define IDD_VIDSEEK                     263
#define IDB_VIDMAN                      264
#define IDB_MUTE                        265
#define IDB_VIDMAN_D                    266
#define IDB_TOOL0_16                    268
#define IDB_TOOL0_16_D                  269
#define IDB_TOOL_DLD_16                 270
#define IDB_TOOL_DLD_16_D               271
#define IDB_TOOL_SCH_16                 272
#define IDB_TOOL_SCH_16_D               273
#define IDB_TOOL_HFE_16                 274
#define IDB_TOOL_HFE_16_D               275
#define IDB_TOOL_SITES_16               276
#define IDB_TOOL_SITES_16_D             277
#define IDB_TOOL_SPIDER_16              278
#define IDB_TOOL_SPIDER_16_D            279
#define IDD_EXTFILTER                   280
#define IDD_WPD_IGNORELIST              281
#define IDD_WPD_IL_ADD                  282
#define IDB_FDM_GETCVER_BTN             283
#define IDI_LOGO2                       284
#define IDD_PRG_SKINS                   285
#define IDD_SM_GENERAL                  286
#define IDD_SM_PASSWORDS                287
#define IDD_SAVEPASSWORD                288
#define IDD_SPREADHELP                  290
#define IDD_SPREADHELP_LINKCODE         291
#define IDM_GCV_BUTTON                  293
#define IDD_TUM_CHANGED                 294
#define IDD_SHUTDOWN_TYPE               296
#define IDD_EXPHIST                     297
#define IDD_DOWNLOAD                    298
#define IDD_DLDDIALOG_HIDE              299
#define IDD_CHOOSEGRP                   300
#define IDD_PRG_MISC                    301
#define IDD_SETUPBATCHNUMBERS           302
#define IDD_UNPACK_SETTINGS             303
#define IDD_UNPACK_PROGRESS             304
#define IDD_UNPACK_ASKOVERWRITE         305
#define IDD_UNPACK_INSTADDPACK          306
#define IDD_CHECKFILEINTEGRITY          307
#define IDD_CHECKFILEINTEGRITY_PROGRESS 308
#define IDD_CHECKFILEINTEGRITY_RESULT   309
#define IDI_TEST_OK                     310
#define IDR_ENG_LNGSTRINGS              311
#define IDD_DLDR_OPINIONS               313
#define IDD_DLDR_COMMUNITY              313
#define IDD_SPREADHELP2                 314
#define IDD_MYMESSAGEBOX                316
#define IDD_OPINIONS                    317
#define IDD_DLDR_MONITOR_SKIPLIST       319
#define IDD_DOWNLOAD_INTEGRITY          320
#define IDI_SETFOLDERDEFAULT            322
#define IDM_UPLOADS                     324
#define IDM_UPLOADS_VIEW                326
#define IDD_BTDLD_GENERAL               328
#define IDD_DLDR_BT                     329
#define IDD_BTDLD_MISC                  332
#define IDD_CREATETORRENTDOWNLOAD       333
#define IDD_PRG_GENERAL_FW              334
#define IDD_PRG_DATA                    335
#define IDD_MAKE_PORTABLE_VER           336
#define IDM_FVDOWNLOADS                 338
#define IDM_FVDOWNLOADS_VIEW            339
#define IDD_FVDOWNLOADS_CONVERT         340
#define IDD_CREATEFVDOWNLOAD            341
#define IDD_CONVERT                     344
#define IDB_DLDSINFO                    345
#define IDB_DLDSINFO_SEL                346
#define IDM_TORRENTS                    349
#define IDM_TORRENTS_VIEW               350
#define IDD_CREATENEWTORRENT            351
#define IDD_BTDLD_FILES                 352
#define IDB_TOOL_BT                     353
#define IDB_TOOL_BT_D                   354
#define IDB_TOOL_BT_16                  355
#define IDB_TOOL_BT_16_D                356
#define IDM_BTFILES                     357
#define IDD_OPTIONS                     358
#define IDD_OPTIONS_GENERAL             359
#define IDD_OPTIONS_GENERAL_HISTORY     360
#define IDD_OPTIONS_GENERAL_MISC        361
#define IDD_OPTIONS_GENERAL_MISC_ADV    362
#define IDD_OPTIONS_DOWNLOADS           363
#define IDD_OPTIONS_DOWNLOADS_NEWDLD    364
#define IDD_OPTIONS_DOWNLOADS_NETWORK   365
#define IDD_OPTIONS_DOWNLOADS_BITTORRENT 366
#define IDD_OPTIONS_DOWNLOADS_MIRRORS   367
#define IDD_OPTIONS_DOWNLOADS_MONITORING 368
#define IDD_OPTIONS_NOTIFICATIONS       369
#define IDD_OPTIONS_SITEMGR             370
#define IDD_BTDLD_SEEDING               371
#define IDD_OPTIONS_DOWNLOADS_TIMELIMIT 372
#define IDI_CLOSEBTN                    373
#define IDD_PI2                         374
#define IDD_PI2_IFREMIND                376
#define IDD_PI2_SURETOCANCEL            377
#define IDD_DL                          378
#define IDD_OPTIONS_DOWNLOADS_FLV       379
#define IDD_CREATEFLVDOWNLOADS          381
#define IDD_CREATEFLVDOWNLOADS_BY_WEBPAGE_URL 382
#define IDB_TIP                         383
#define IDB_CLOSE                       384
#define IDD_ELEVATE_REQ                 385
#define IDD_TUM_SETTINGS_PERDIRECTION   386
#define IDD_SPECIFYNETSPEEDVALUE        387
#define IDD_CONNECTIONSPEEDINFO         388
#define IDD_CREATETPDOWNLOAD            389
#define IDD_TPDLD_GENERAL               390
#define IDD_TORRENTMOVE                 492
#define IDD_DIALOG2                     495
#define IDD_UNHEXC2                     495
#define IDC_URL                         1001
#define IDC_BUTTON2                     1003
#define IDC_SETTIME                     1003
#define IDC_CLEARHISTORY                1003
#define IDC_MOREEXAMPLES                1003
#define IDC_HTMLSPIDER_DEFDLDSTGS       1003
#define IDC_FFPORTVER                   1003
#define IDC_BUTTON3                     1004
#define IDC_RAD_ENABLE                  1004
#define IDC_CLEARHISTORY2               1004
#define IDC_BT_DEFDLDSTGS               1004
#define IDC_IGNOREALL                   1004
#define IDC_BUTTON4                     1005
#define IDC_RAD_DISABLE                 1005
#define IDC_BUTTON5                     1006
#define IDC_AUTHORIZATION               1006
#define IDC_RAD_INVERT                  1006
#define IDC_USER                        1007
#define IDC_PASSWORD                    1008
#define IDC_GROUPS                      1009
#define IDC_OUTFOLDER                   1010
#define IDC_GROUPS2                     1010
#define IDC_SAVEAS                      1011
#define IDC_CREATEGROUP                 1012
#define IDC_CHOOSEFOLDER                1013
#define IDC_CREATEGROUP2                1013
#define IDC_COMMENT                     1014
#define IDC_PAUSEBETWEENSPIN            1014
#define IDC__DLGFRAME                   1014
#define IDC_STARTNOW                    1015
#define IDC_PAUSEBETWEEN                1015
#define IDC_STARTMANUAL                 1016
#define IDC_MAXATTEMPTS                 1016
#define IDC_PAUSEBETWEEN2               1016
#define IDC_MAXCONNSPERSERVER           1016
#define IDC_STARTSCHEDULE               1017
#define IDC_MAXATTEMPTSSPIN             1017
#define IDC_PAUSEBETWEENSPIN2           1017
#define IDC_MAXCONNSPERSERVERSPIN       1017
#define IDC_TIMEOUT                     1018
#define IDC_MAXDLDSVAL                  1018
#define IDC_FROM                        1018
#define IDC_DLDTYPE                     1018
#define IDC__DLGCAPTION                 1018
#define IDC_TIMEOUTSPIN                 1019
#define IDC_MAXDLDSSPIN                 1019
#define IDC_NUMBER                      1019
#define IDC_OUTFOLDER_SETDEFAULT        1019
#define IDC_SECTMINSIZE                 1020
#define IDC_MAXNUMBERVAL                1020
#define IDC_TIMEOUT2                    1020
#define IDC__USER                       1021
#define IDC_MAXNUMBERSPIN               1021
#define IDC_LOWSPEED_DURATION           1021
#define IDC_TIMEOUTSPIN2                1021
#define IDC__PASSWORD                   1022
#define IDC_SECTMAXCOUNT                1022
#define IDC_SECTMAXCOUNTSPIN            1023
#define IDC_FROMSPIN                    1023
#define IDC_LIST1                       1024
#define IDC_TRAFFICLIMITVAL             1024
#define IDC_SELDLDS                     1024
#define IDC_LOG                         1024
#define IDC_TO                          1024
#define IDC_LIST                        1024
#define IDC__WARN                       1024
#define IDC_MIRRS                       1024
#define IDC_SOUNDS                      1024
#define IDC_TRACKER_LIST                1024
#define IDC_FLVLIST                     1024
#define IDC_MESSAGE                     1025
#define IDC_UNSELDLDS                   1025
#define IDC_TOSPIN                      1025
#define IDC_MAXSIZEVAL                  1025
#define IDC_LOWSPEED_DURATIONSPIN       1025
#define IDC_INFO                        1026
#define IDC_MESSAGE2                    1026
#define IDC_WB                          1026
#define IDC_GRPNAME                     1027
#define IDC_WBSPIN                      1027
#define IDC__FIRM                       1027
#define IDC_GRPFOLDER                   1028
#define IDC_STEP                        1028
#define IDC__DOWNLOAD                   1028
#define IDC_GRPEXTS                     1029
#define IDC_EDIT1                       1029
#define IDC_PROXYNAME                   1029
#define IDC_EXT                         1029
#define IDC_PROGNAME                    1029
#define IDC_EXTS                        1029
#define IDC_UPDATEURL                   1029
#define IDC_NAME                        1029
#define IDC_STEPSPIN                    1029
#define IDC_ARGS                        1029
#define IDC_ADDR                        1029
#define IDC_HTMLCODE                    1029
#define IDC_NUMBERS                     1029
#define IDC_DSTFOLDER                   1029
#define IDC_CHECKSUM                    1029
#define IDC_FILEINFO                    1029
#define IDC_TORRENTFILE                 1029
#define IDC_FOLDER                      1029
#define IDC_MALREPSMINIMUM              1029
#define IDC_WPURL                       1029
#define IDC_STRSPEED                    1029
#define IDC_SERVERTYPE                  1030
#define IDC_PROTOCOLS                   1030
#define IDC_ARGUMENTS                   1030
#define IDC_CREATEEXT                   1030
#define IDC_VIREXTS                     1030
#define IDC_SERVERS                     1030
#define IDC_EDIT2                       1031
#define IDC_PORT                        1031
#define IDC__VER                        1031
#define IDC_MALREPSMINIMUM2             1031
#define IDC_CHECK2                      1032
#define IDC_USEEXT                      1032
#define IDC_USEMAXATTEMPTS              1032
#define IDC_AUTODEL                     1032
#define IDC_CLOSEASMINIMIZE             1032
#define IDC_USEMAXCONN                  1032
#define IDC_ELON                        1032
#define IDC_VALIDSUBDOMAINS             1032
#define IDC_DISABLE                     1032
#define IDC_FILEAUTO                    1032
#define IDC_KEEP                        1032
#define IDC_MAXMIRRORS                  1032
#define IDC_SAVEDLTOGRPFOLDER           1032
#define IDC_USESOUNDS                   1032
#define IDC_DELRECTHATEXISTS            1032
#define IDC_USEMAX                      1032
#define IDC_LOCALNAME                   1032
#define IDC_USETIME                     1032
#define IDC_DONTMONSMALL                1032
#define IDC_ASKFORST                    1032
#define IDC_CHECKIFMAL                  1032
#define IDC_SET_AS_DEF                  1032
#define IDC_ENABLE_UPNP                 1032
#define IDC_COMBO1                      1033
#define IDC_USERAGENT                   1033
#define IDC_SECTMINSIZEDIM              1033
#define IDC_AER                         1033
#define IDC_WHENDEL                     1033
#define IDC_CT                          1033
#define IDC_WTS                         1033
#define IDC_EVERYDIM                    1033
#define IDC_CHECK9                      1033
#define IDC_STARTMINIMIZED              1033
#define IDC_ENTRY                       1033
#define IDC_SITE                        1033
#define IDC_DLIMAGESFROMOTHERSITES      1033
#define IDC_DELETE                      1033
#define IDC__LICENSE                    1033
#define IDC_MAXNUMBER                   1033
#define IDC_FINDWHAT                    1033
#define IDC_KEEP2                       1033
#define IDC_DONTSTOREPAGES              1033
#define IDC_SKIN                        1033
#define IDC_A                           1033
#define IDC_MIRRSERVERS                 1033
#define IDC_TYPE                        1033
#define IDC_HANGUP_TOUT                 1033
#define IDC_ALGORITHM                   1033
#define IDC_DISPLAYOPINIONS             1033
#define IDC_PLACEATTOP                  1033
#define IDC_SOURCE                      1033
#define IDC_RATIO_LIST                  1033
#define IDC_CONNECTIONSPEED             1033
#define IDC_CHECK1                      1034
#define IDC_USEHTTP11                   1034
#define IDC_LIMITTRAFFIC                1034
#define IDC_RESERVESPACE                1034
#define IDC_TUM                         1034
#define IDC_SUN                         1034
#define IDC_USECONFIRMATION             1034
#define IDC_DONTASKAGAIN                1034
#define IDC_RETREIVEADDINFO             1034
#define IDC_CLIPBOARD                   1034
#define IDC_AUTOCHECK                   1034
#define IDC_USELOGIN                    1034
#define IDC_AUTO                        1034
#define IDC_DLFILES                     1034
#define IDC_DETECTACTIVITY              1034
#define IDC_VALIDHTTP                   1034
#define IDC_DETAILEDLOG                 1034
#define IDC_USEBALLOON                  1034
#define IDC_GROUPBYEXT                  1034
#define IDC_DLTHIS                      1034
#define IDC_USEHIST                     1034
#define IDC_NOCOMPLETED                 1034
#define IDC_USE                         1034
#define IDC_DONTUSE                     1034
#define IDC_FILENAME                    1034
#define IDC_LISTOFDLDS                  1034
#define IDC_SUBFOLDERS                  1034
#define IDC_USEROLLBACK                 1034
#define IDC_ALLOWICONS                  1034
#define IDC_DONTSUGGEST                 1034
#define IDC_DONTSHOW                    1034
#define IDC_REMEMBER                    1034
#define IDC_AUTOCLOSE                   1034
#define IDC_EXIT_TOUT                   1034
#define IDC_NEVERSHOWTHISIFTESTOK       1034
#define IDC_SWITCHTOOPINIONS            1034
#define IDC_MODIFYIEUSERAGENT           1034
#define IDC_ICFR                        1034
#define IDC_VIDEOSIZE                   1034
#define IDC_CHECK3                      1035
#define IDC_USEPASSIVEMODE              1035
#define IDC_TRAFFICLIMITDIM             1035
#define IDC_DONTRESTARTIFNORESUME       1035
#define IDC_USEMAXCONNSPERSERVER        1035
#define IDC_DIALCONNECTION              1035
#define IDC_TUE                         1035
#define IDC_USEWAIT                     1035
#define IDC_PASSIVEMODE                 1035
#define IDC_IE                          1035
#define IDC_AUTOSTART                   1035
#define IDC_USEDEFGROUP                 1035
#define IDC_DLFILESFROMOTHERSITES       1035
#define IDC_SIZEINBYTES                 1035
#define IDC_CALCSPEED                   1035
#define IDC_DLPAGE                      1035
#define IDC_APPEND                      1035
#define IDC_CONFIRMDELETION             1035
#define IDC_COMPONLY                    1035
#define IDC_HISTOFDLDS                  1035
#define IDC_ALLOWBITMAPS                1035
#define IDC_DELCOMPLETED                1035
#define IDC_Z                           1035
#define IDC_SHUTDOWN_TOUT               1035
#define IDC_AUTOLAUNCH                  1035
#define IDC_DISABLEFORBATCHDLDS         1035
#define IDC_USE2                        1035
#define IDC_M_FIREFOX                   1035
#define IDC_ORBIT_MANAGER               1035
#define IDC_ENABLE_NAT_PMP              1035
#define IDC_ENABLE_NATPMP               1035
#define IDC_USEZIPPREVIEW               1036
#define IDC_RADIO1                      1036
#define IDC_BINARY                      1036
#define IDC_SCR                         1036
#define IDC_TRAFFICLIMITDIM2            1036
#define IDC_TRAFFICLIMITDIMENSION       1036
#define IDC_SHUTDOWNTYPE                1036
#define IDC_MONWITHEXTS                 1036
#define IDC_FULLDISTRIB                 1036
#define IDC_ELDL                        1036
#define IDC_VALIDHTTPS                  1036
#define IDC_VIRCHECK                    1036
#define IDC_DLALL                       1036
#define IDC_FOLDERSONLY                 1036
#define IDC_ALL                         1036
#define IDC_BYPASSCOMPLETED             1036
#define IDC_CHECK10                     1036
#define IDC_SKIPEXTS                    1036
#define IDC_ASK                         1036
#define IDC_SUGGESTTOCHANGEDEFFOLDER    1036
#define IDC_REMIND_NEXTSTART            1036
#define IDC_SHOW                        1036
#define IDC_LAUNCHDLD_TOUT              1036
#define IDC_IGNORE                      1036
#define IDC_SETOFNUMBERS                1036
#define IDC_RESTARTIFSPEEDLOW           1036
#define IDC_AUTOINSTALL                 1036
#define IDC_KEEP_1                      1036
#define IDC_NEWGRP_0                    1036
#define IDC_QUALITY                     1036
#define IDC_UNLIMITED_SEEDING           1036
#define IDC_M_OPERA                     1036
#define IDC_MNC_MANAGEAUTO              1036
#define IDC_ASCII                       1037
#define IDC_RADIO2                      1037
#define IDC_HANGUPIFLESS                1037
#define IDC_IGNOREWITHEXTS              1037
#define IDC_UPGDISTRIB                  1037
#define IDC_ELDONTDL                    1037
#define IDC_DECBYLEVEL                  1037
#define IDC_VALIDFTP                    1037
#define IDC_USECREATEEXT                1037
#define IDC_DLSELECTED                  1037
#define IDC_ALLINLIST                   1037
#define IDC_MAXSIZEDIM                  1037
#define IDC_LEAVE                       1037
#define IDC_REMIND_IN3DAYS              1037
#define IDC_DONTSHOW_                   1037
#define IDC_SHOWDLDDLG                  1037
#define IDC_THISONLY                    1037
#define IDC_SINGLENUMBER                1037
#define IDC_DISABLEWDTASKAFTEREXEC      1037
#define IDC_SKIPEXTS2                   1037
#define IDC__SKIPSERVERS                1037
#define IDC_KEEP_2                      1037
#define IDC_NEWGRP_1                    1037
#define IDC_DELRECTHATEXISTS2           1037
#define IDC_LIMIT_BY_RATIO              1037
#define IDC_MNC_SETTO                   1037
#define IDC_SETTOLIGHT                  1038
#define IDC_USESOCKS                    1038
#define IDC_ASCIIFOREXTS                1038
#define IDC_FORCEEXIT                   1038
#define IDC_ADDTOIEMENU                 1038
#define IDC_SELECTED                    1038
#define IDC_USEHIDDENFLAG               1038
#define IDC_REMIND_NEVER                1038
#define IDC_DONTSAVELOGS                1038
#define IDC_RADIO3                      1038
#define IDC_DONTSHOW_FORTHISDLD         1038
#define IDC_REMIND_IN3DAYS2             1038
#define IDC_DONTSHOWAGAIN               1038
#define IDC_AUTOTURNOFF                 1038
#define IDC_NEWGRP_2                    1038
#define IDC_DLVIDEO                     1038
#define IDC_COMPONLY2                   1038
#define IDC_M_NETSCAPE                  1038
#define IDC_MNCPS_MANAGEAUTO            1038
#define IDC_REFERER                     1039
#define IDC_USEMAXDLDS                  1039
#define IDC_OPERA                       1039
#define IDC_APPENDCOMMENT               1039
#define IDC_USEWC                       1039
#define IDC_CHECKEXISTS                 1039
#define IDC_M_SAFARI                    1039
#define IDC_MNCPS_SETTO                 1039
#define IDC_USECOOKIE                   1040
#define IDC_NETSCAPE                    1040
#define IDC_DISPLAYOPINIONS2            1040
#define IDC_M_CHROME                    1040
#define IDC_MNT_MANAGEAUTO              1040
#define IDC_ASCIIEXTS                   1041
#define IDC_IEXPLORE                    1041
#define IDC_FIREFOX                     1041
#define IDC_SWITCHTOOPINIONS2           1041
#define IDC_SHOWGETITBTN                1041
#define IDC_MNT_SETTO                   1041
#define IDC_CHECK4                      1042
#define IDC_MON                         1042
#define IDC_USEFTPPASSIVE               1042
#define IDC_IE2                         1042
#define IDC_RECALCSPEED                 1042
#define IDC_RESTARTCOMPDLS              1042
#define IDC_DELETED                     1042
#define IDC_USEZIP                      1042
#define IDC_RENAMEATRESTART             1042
#define IDC_DONTSENDLIST                1042
#define IDC_PREVENT_STANDBY             1042
#define IDC_SKIN2                       1042
#define IDC_LISTRECENTDLDS              1042
#define IDC_USE_ONDONE_WNDS             1042
#define IDC_IGNOREALLRESTRICTIONS       1043
#define IDC_CHECK5                      1043
#define IDC_WED                         1043
#define IDC_DONTIFSIZEUNK               1043
#define IDC_SILENT                      1043
#define IDC_USESIZE                     1043
#define IDC_DONTSENDLIST2               1043
#define IDC_ALLOWICONS2                 1043
#define IDC_CHECKIFMAL2                 1043
#define IDC_USETIMEOUT2                 1043
#define IDC__PROTOCOL                   1044
#define IDC_MOZILLA                     1044
#define IDC_ALLOWBITMAPS2               1044
#define IDC__ADDRESS                    1045
#define IDC_SAFARI                      1045
#define IDC__PORT                       1046
#define IDC_CHECK6                      1046
#define IDC_THU                         1046
#define IDC_CHROME                      1046
#define IDC_CHECKIFDLDISMIRR            1046
#define IDC_SHOWTIPS                    1046
#define IDC_FILENOTFOUND                1047
#define IDC_CHECK7                      1047
#define IDC_FRI                         1047
#define IDC_ACCDENIED                   1048
#define IDC_MODE                        1048
#define IDC_CHECK8                      1048
#define IDC_SAT                         1048
#define IDC_MAXCONNS                    1049
#define IDC_MAXREDIALS                  1049
#define IDC_MAXCONNSSPIN                1050
#define IDC_MAXREDIALSSPIN              1050
#define IDC__TUR                        1051
#define IDC_REDIALPAUSE                 1051
#define IDC_AUTOSAVE                    1052
#define IDC_REDIALPAUSESPIN             1052
#define IDC_AUTOSAVESPIN                1053
#define IDC_TIMES                       1053
#define IDC_TIMESSPIN                   1054
#define IDC_WC_SIZE                     1054
#define IDC_WC_SPIN                     1055
#define IDC_HTS                         1056
#define IDC__PROGNAME                   1056
#define IDC_CHOOSENAME                  1057
#define IDC_DATETIMEPICKER1             1057
#define IDC_TIME                        1057
#define IDC_TOSEL                       1058
#define IDC_DATETIMEPICKER2             1058
#define IDC_DATE                        1058
#define IDC_TOUNSEL                     1059
#define IDC_EVERY                       1059
#define IDC_HANGUPALL                   1060
#define IDC_EVERYSPIN                   1060
#define IDC__HANGUP                     1061
#define IDC_RADIO4                      1061
#define IDC_DURING                      1061
#define IDC_USEPAUSE                    1062
#define IDC_COMBO2                      1062
#define IDC_EVENT                       1062
#define IDC_TRACKERS                    1062
#define IDC__CONNECTION                 1063
#define IDC_STARTTIME                   1063
#define IDC_CONNECTION                  1064
#define IDC__DIALINGTO                  1064
#define IDC_DURINGSPIN                  1064
#define IDC__TUM                        1065
#define IDC_LOWSPEED                    1065
#define IDC_BPS                         1066
#define IDC__DURING                     1066
#define IDC_TRYAGAIN                    1067
#define IDC__LOWSPEED                   1067
#define IDC_FILESIZE                    1067
#define IDC_NOMORETHAN                  1068
#define IDC__MINUTES                    1068
#define IDC__DIALING                    1069
#define IDC__BPS                        1069
#define IDC__IFSUCCESSFULL              1070
#define IDC__TIMES                      1071
#define IDC__SECONDS                    1071
#define IDC__ARGUMENTS                  1072
#define IDC__TYPE                       1073
#define IDC__MESSAGE                    1073
#define IDC_DLGICON                     1074
#define IDC_RESTARTDLDIFDONE            1074
#define ID_CANCEL2                      1075
#define IDC_REWRITE                     1076
#define IDC_RENAME                      1077
#define IDC_RESUME                      1078
#define IDC_STOP                        1079
#define IDC_RESTART                     1080
#define IDC_ADJUST                      1081
#define IDC_LAUNCH                      1081
#define IDC_YES                         1082
#define IDC_NO_                         1083
#define IDC_YESFORALL                   1083
#define IDC_CANCEL                      1084
#define IDC_YESTOALL                    1084
#define IDC__GENERAL                    1085
#define IDC_NOTOALL                     1085
#define IDC_NOFORALL                    1085
#define IDC__URL                        1086
#define IDC__SAVEDAS                    1087
#define IDC_TREE1                       1088
#define IDC_FILES                       1088
#define IDC_PAGELIST                    1088
#define IDC_SELECTFOLDER                1089
#define IDC_UNSELECTFOLDER              1090
#define IDC_ALTNOTPRESSED               1090
#define IDC_ALTPRESSED                  1091
#define IDC_MINTOTRAY                   1091
#define IDC_HOMEPAGE                    1092
#define IDC_ALLOWIETODL                 1092
#define IDC_HIDEFWWFS                   1092
#define IDC_MAILTO                      1093
#define IDC_PROGRESS                    1094
#define IDC_DESC                        1095
#define IDC_TIMELEFT                    1096
#define IDC__SIZE                       1097
#define IDC__SPEED                      1098
#define IDC__SIZEAVAIL                  1098
#define IDC__TIMELEFT                   1099
#define IDC_AUTOUPDATES_INSTALL         1100
#define IDC_CONNECT                     1100
#define IDC_AUTOUPDATES_NOTIFYONLY      1101
#define IDC__PAUSEBETWEEN               1101
#define IDC_AUTOUPDATES_TURNOFF         1102
#define IDC__TIMEOUT                    1102
#define IDC__SECTMINSIZE                1103
#define IDC__SECTMAXCOUNT               1104
#define IDC__GROUP                      1105
#define IDC__SAVETO                     1106
#define IDC__PARENTGROUP                1106
#define IDC__SAVEAS                     1107
#define IDC__COMMENT                    1108
#define IDC__LIST                       1109
#define IDC__DLDTYPE                    1109
#define IDC__FOLDER                     1110
#define IDC__EXTS                       1111
#define IDC__AUTOSAVE                   1112
#define IDC__WHENDEL                    1113
#define IDC__MODEADJUSTMENT             1114
#define IDC__IFEXISTS                   1115
#define IDC__IFSIZECHANGED              1116
#define IDC__IDAS                       1117
#define IDC__REFERER                    1118
#define IDC__VERSION                    1119
#define IDC_BUTTON1                     1120
#define IDC_GETKEY                      1120
#define IDC_REGNOW                      1120
#define IDC_QSIZE                       1120
#define IDC_RESULTS                     1120
#define IDC_DELSELECTED                 1120
#define IDC_ADDMIRROR                   1120
#define IDC_CUSTOMIZE                   1120
#define IDC_DELALL                      1120
#define IDC_SWITCHDLHIST                1120
#define IDC_VIEWLINKCODE                1120
#define IDC_COPYTOCLIPBOARD             1120
#define IDC_HIDE                        1120
#define IDC_BROWSE                      1120
#define IDC_RESTARTDOWNLOAD             1120
#define IDC_CHECKUNCHECKALL             1120
#define IDC_MACROSES                    1120
#define IDC_ADJUST_FW                   1120
#define IDC_VIEW_S_SITES                1120
#define IDC_SETTINGS                    1120
#define IDC_SETGRPSFLDR                 1120
#define IDC_FILE                        1120
#define IDC_CHECK_UNCHECK_ALL           1120
#define ID_REMIND_ME_LATER              1120
#define IDC_MEASUREAGAIN                1120
#define IDC_CONNECTIONSPEEDINFO         1120
#define IDC_RETRY                       1120
#define IDC_ORDER                       1121
#define IDC__LICTO                      1121
#define IDC_SHAREIT                     1121
#define IDC_QUERYSIZE                   1121
#define IDC_FINDMIRRORS                 1121
#define IDC_COPYTOCLIPBOARD2            1121
#define IDC_SKIPLIST                    1121
#define IDC_SETTINGS2                   1121
#define IDC_KEY                         1122
#define IDC_CALCMIRRSPEED               1122
#define IDC_FILTER                      1122
#define IDC_OPEN                        1122
#define IDC_OPENFILE                    1122
#define IDC_SETNUMBERS                  1122
#define IDC_ADD_TRACKER                 1122
#define IDC__NAME                       1123
#define IDC_PROPERTIES                  1123
#define IDC_OPENFOLDER                  1123
#define IDC_REMOVE_TRACKER              1123
#define IDC__KEY                        1124
#define IDC_SAVE_TRACKERS               1124
#define IDC__SITE                       1125
#define IDC_RESTORE_TRACKERS            1125
#define IDC__NAGMSG                     1126
#define IDC_CLEAR_TRACKERS              1126
#define IDC__BUYMSG                     1127
#define IDC__KEYNOTE                    1128
#define IDC__DEFPRIOR                   1129
#define IDC__START                      1130
#define IDC__NETWORK                    1132
#define IDC__ERRORS                     1133
#define IDC__SECTIONS                   1134
#define IDC__NETUSAGERESTR              1135
#define IDC__TRANSFERMODE               1136
#define IDC__GETFROM                    1137
#define IDC__SETTINGS                   1138
#define IDC__LOCALFILE                  1139
#define IDC__INETSERV                   1140
#define IDC__STOPONERRS                 1141
#define IDC__TUMS                       1142
#define IDC__LISTOFDLDS                 1143
#define IDC__MIN                        1144
#define IDC__MONITORFOR                 1145
#define IDC__STARTUP                    1146
#define IDC__SYSTEM                     1147
#define IDC__WELCOMETONOW               1148
#define IDC__UPDATE                     1148
#define IDC__MASTERDESC                 1149
#define IDC__CONNTYPE                   1150
#define IDC__CONFIRMATION               1151
#define IDC__USINGMAY                   1152
#define IDC__LOGINREQ                   1153
#define IDC__SAVEDIN                    1154
#define IDC_SAVEDIN                     1155
#define IDC__HTMLEXTS                   1156
#define IDC_HTMLEXTS                    1157
#define IDC_DLSTYLES                    1158
#define IDC_DLWPFROMOTHERSITES          1159
#define IDC_DLIMAGES                    1160
#define IDC_USEHTM                      1160
#define IDC__DEPTH                      1161
#define IDC_DEPTH                       1162
#define IDC_DEPTHSPIN                   1163
#define IDC__ELIMINATION                1164
#define IDC__PAGES                      1165
#define IDC__IMAGES                     1166
#define IDC_TRIALPROGRESS               1167
#define IDC__DTDL                       1168
#define IDC__HOMEPAGE                   1169
#define IDC__SUPPORT                    1170
#define IDC__VALIDFOR                   1170
#define IDC__FROM                       1172
#define IDC__TO                         1173
#define IDC__WB                         1174
#define IDC__STEP                       1175
#define IDC__SAMPLE                     1176
#define IDC__NUMBER                     1176
#define IDC__ARGS                       1177
#define IDC__FROM2                      1177
#define IDC__TO2                        1178
#define IDC_VIRNAME                     1179
#define IDC_CHOOSEVIR                   1180
#define IDC__UEICON                     1181
#define IDC__MSG                        1182
#define IDC_DONTASK                     1183
#define IDC__MSG1                       1183
#define IDC__SUPPORT1                   1184
#define IDC__MSG2                       1184
#define IDC__SUPPORT2                   1185
#define IDC__MSG4                       1186
#define IDC__MSG5                       1187
#define IDC_URLLIST                     1188
#define IDC__MSG6                       1188
#define IDC__MSG7                       1189
#define IDC__SEC                        1190
#define IDC__MSG8                       1190
#define IDC_MAXMIRRORSVAL               1191
#define IDC__SEC2                       1191
#define IDC_MAXMIRRORSSPIN              1192
#define IDC_RECALCVAL                   1193
#define IDC_RECALCSPIN                  1194
#define IDC__DONTSEARCH                 1195
#define IDC_FILEMINSIZE                 1196
#define IDC_FILEMINSIZEDIM              1197
#define IDC__SETGROUPTO                 1198
#define IDC__SETGROUPTO2                1199
#define IDC_DAYS                        1200
#define IDC_DAYSSPIN                    1201
#define IDC__DAYS                       1202
#define IDC__DOWNLOADS                  1203
#define IDC_DAYS2                       1203
#define IDC_MAXVAL                      1204
#define IDC_DAYSSPIN2                   1204
#define IDC_MAXVALSPIN                  1205
#define IDC__DAYS2                      1205
#define IDC__FINDWHAT                   1206
#define IDC__SEARCHIN                   1207
#define IDC__FINDWHERE                  1208
#define IDC__MINIMUM                    1209
#define IDC__MAXIMUM                    1210
#define IDC_MINSIZEVAL                  1211
#define IDC_MINSIZEDIM                  1212
#define IDC__SEARCHINGROUP              1213
#define IDC_TOOL                        1213
#define IDC__TOOL                       1213
#define IDC_SLIDER1                     1214
#define IDC_VOLUME                      1214
#define IDC_TRANCPARENCY1               1214
#define IDC__MUTE                       1215
#define IDC_TRANCPARENCY2               1215
#define IDC_SEEK                        1216
#define IDC__DURATION                   1217
#define IDC__FILENAME                   1218
#define IDC__SIZEVAL                    1219
#define IDC__FILESIZE                   1219
#define IDC__SIZEAVAILVAL               1220
#define IDC__RST                        1220
#define IDC__DURATIONVAL                1221
#define IDC__DOWNLOADED                 1221
#define IDC__MEDIAINFO                  1222
#define IDC__VOLUME                     1223
#define IDC_IGNORELIST                  1224
#define IDC_ROLLBACKSIZE                1225
#define IDC__ROLSIZE                    1226
#define IDC__BYTES                      1227
#define IDC_SMALLSIZE                   1228
#define IDC__KBYTES                     1229
#define IDC__SKIN                       1230
#define IDC__AFTERRESTART               1231
#define IDC__MIRRSERVER                 1232
#define IDC__TEXT1                      1233
#define IDC__TEXT2                      1234
#define IDC__TEXT3                      1235
#define IDC_LAUNCHWHENDONE              1236
#define IDC__TEXT4                      1236
#define IDC_GENERATEINFOFILE            1237
#define IDC_RETRFILEDATE                1238
#define IDC__FDM                        1239
#define IDC_I_HEAVY                     1240
#define IDC_I_MEDIUM                    1241
#define IDC_I_LIGHT                     1242
#define IDC__HEAVY                      1243
#define IDC_HEAVY_DESC                  1244
#define IDC__MEDIUM                     1245
#define IDC__MEDIUM_DESC                1246
#define IDC__LIGHT                      1247
#define IDC__LIGHT_DESC                 1248
#define IDC__TOPMSG                     1249
#define IDC__VOLPERC                    1250
#define IDC__EXPORT                     1250
#define IDC__EXPORTOPTS                 1251
#define IDC_COMPLETEDONLY               1252
#define IDC__PROGRESS                   1253
#define IDC__SAVEDIN_                   1254
#define IDC__FILESIZE_                  1255
#define IDC__RESUMESUPPORT_             1256
#define IDC__DOWNLOADED_                1257
#define IDC_SPEED_                      1258
#define IDC_TIMELEFT_                   1259
#define IDC__URL_                       1260
#define IDC__S1                         1260
#define IDC_DIALOG_ICON                 1261
#define IDC__EXIT                       1262
#define IDC__SHUTDOWN                   1263
#define IDC__LAUNCHDLD                  1264
#define IDC__TOUTSFORCONFS              1265
#define IDC__SETOFNUMBERS               1266
#define IDC_SET                         1267
#define IDC__EXTRACTING                 1269
#define IDC__DSTFOLDER                  1270
#define IDC__INFOMSG                    1271
#define IDC__ALGORITHM                  1272
#define IDC__CHECKSUM                   1273
#define IDC__ICON                       1273
#define IDC__RESULTMSG                  1274
#define IDC__MSG3                       1275
#define IDC__MSG9                       1276
#define IDC_EXPLORER1                   1277
#define IDC__WC_MB                      1278
#define IDC_PERFORMCHECKWHENDONE        1279
#define IDC__CHECKSUMOFTHISFILE         1280
#define IDC__IFCHECKFAILED              1281
#define IDC__HASH                       1283
#define IDC__TORRENTURL                 1283
#define IDC_SAVEIN                      1284
#define IDC_HASH                        1285
#define IDC_ENABLE                      1286
#define IDC_LIMIT                       1287
#define IDC_LIMITVAL                    1288
#define IDC_LIMITDIM                    1289
#define IDC_TRAFFICMODESTAB             1290
#define IDC_UPLLIMITVAL                 1291
#define IDC_UPLLIMITVALSPIN             1292
#define IDC_PORT_FROM                   1293
#define IDC_PORT_FROM_SPIN              1294
#define IDC_PORT_TO                     1295
#define IDC_LIMITUPLOADS                1296
#define IDC_PORT_TO_SPIN                1297
#define IDC_USE_DHT                     1298
#define IDC__USEPORTS                   1299
#define IDC_DESCRIPTION                 1300
#define IDC__FILE                       1300
#define IDC_MAXHALFSVAL                 1300
#define IDC_DROPBOX                     1301
#define IDC_MAXHALFSSPIN                1301
#define IDC_DLINFO                      1302
#define IDC_LIMITCONNS                  1302
#define IDC__TRANCPARENCY1              1303
#define IDC_CONNSLIMITVAL               1303
#define IDC__TRANCPARENCY1_VAL          1304
#define IDC_CONNSLIMITVALSPIN           1304
#define IDC__TRANCPARENCY2              1305
#define IDC__TRANCPARENCY2_VAL          1306
#define IDC__PVDESC                     1307
#define IDC_ASSOCWITHMAGNET             1308
#define IDC_ASSOCWITHTORRENT            1309
#define IDC__S0                         1310
#define IDC_S_SITES                     1311
#define IDC_CONVERT                     1312
#define IDC_FORMAT                      1313
#define IDC__FORMAT                     1314
#define IDC__VIDEOSIZE                  1315
#define IDC__QUALITY                    1316
#define IDC_USE_AUTO_CONVERT            1317
#define IDC_SWITCH_AUTO                 1318
#define IDC__GRPFORNEWDLD               1319
#define IDC_DISABLE_SEEDING             1320
#define IDC__DATADESC                   1321
#define IDC__MAXHALFS                   1322
#define IDC_PIECE_SIZE                  1323
#define IDC_SEED                        1324
#define IDC__SOURCE                     1327
#define IDC__PIECE_SIZE                 1328
#define IDC__TRACKERS                   1329
#define IDC__SKINS                      1331
#define IDC__FLOATING_WINDOWS           1332
#define IDC__SERVICE_FILES              1333
#define IDC__FDM_COMMUNITY              1334
#define IDC__PASSWORDS                  1335
#define IDC_ENABLE_SEEDING              1336
#define IDC_STATIC0                     1337
#define IDC_DONTCHECKAGAIN              1339
#define IDC_SETLIMIT                    1340
#define IDC__WEBPAGE                    1342
#define IDC_CNVRT_SETTINGS              1343
#define IDC_ENABLE_MONITORING           1344
#define IDC__WARNING                    1345
#define IDC__FLVONTHISPAGE              1346
#define IDC__NOTE                       1347
#define IDC_M_IE                        1348
#define IDC_M_SEAMONKEY                 1349
#define IDC_STATIC_MANAGER              1351
#define IDC_STATIC_PROCESSED            1352
#define IDC_STATIC_ORBIT                1353
#define IDC_ORBIT_SUCCESSFUL            1354
#define IDC_MTORRENET_MANAGER           1354
#define IDC_ORBIT_FAILED                1355
#define IDC_STATIC_CHOOSE_MANAGERS      1355
#define IDC_ORBIT_UNPROCESSED           1356
#define IDC__STRSPEED                   1356
#define IDC_RESTRTRAFF                  1356
#define IDC_ORBIT_TOTAL                 1357
#define IDC_RESTTRAFFSSPIN              1357
#define IDC_SPIN1                       1357
#define IDC_STRSPEED_SPIN               1357
#define IDC_STATIC_MTORRENT             1358
#define IDC_MNC_VALUE                   1358
#define IDC_MTORRENT_SUCCESSFUL         1359
#define IDC_MNC_VALUESPIN               1359
#define IDC_MTORRENT_FAILED             1360
#define IDC_MNCPS_VALUE                 1360
#define IDC_MTORRENT_UNPROCESSED        1361
#define IDC_MNCPS_VALUESPIN             1361
#define IDC_MTORRENT_TOTAL              1362
#define IDC__TRAFFRESTR                 1362
#define IDC__PERCOFCONNSPEED            1363
#define IDC_MNT_VALUE                   1364
#define IDC__MAXNUMBEROFCONNS           1365
#define IDC__MAXNUMBEROFCONNSPERSERV    1366
#define IDC__MAXNUMBEROFTASKS           1367
#define IDC_MNT_VALUESPIN               1368
#define IDC_MODESTAB                    1369
#define IDC__CONNECTIONSPEED            1370
#define IDC__TUMSETTINGS                1371
#define IDC__TUMPERDIRSETTINGS_PLACE    1373
#define IDC_DIM                         1374
#define IDC_VAL                         1375
#define IDC__DOWNSPEEDVAL               1376
#define IDC__UPSPEEDVAL                 1377
#define IDC__DOWNLOADSPEED              1378
#define IDC__UPLOADSPEED                1379
#define IDC_INBITS                      1380
#define IDC_ABORTALL                    1558
#define IDC_LOCAL_PEER                  1559
#define IDC__COPYRIGHT                  1900
#define IDC__REGTO                      1901
#define IDC_USEMAXCONNS                 2034
#define IDC_GETFROMIE                   2036
#define IDC_ONCE                        2036
#define IDC_FROMFIREFOX                 2037
#define IDC_DAILY                       2037
#define IDC_MANUALLY                    2038
#define IDC_ONEVERY                     2038
#define IDC_DONTUSEPROXY                2039
#define IDC_ONEVENT                     2039
#define IDC_NO2                         2100
#define IDR_FDMUIWINDOW                 3000
#define ID_TEST                         32771
#define ID_GRPDELETE                    32785
#define ID_GRPPROPERTIES                32786
#define ID_GRPCREATE                    32787
#define ID_GRPSTARTALL                  32788
#define ID_GRPSTOPALL                   32789
#define ID_GRPDELETEALL                 32790
#define ID_GRPDELETEALLSUCCESSFUL       32791
#define ID_CLEAR                        32797
#define ID_AUTOSCROLL                   32798
#define ID_OPENGROUPFOLDER              32799
#define ID_DLDROPTIONS                  32801
#define ID_DLDDEFOPTIONS                32802
#define ID_TUM_HEAVY                    32803
#define ID_TUM_LIGHT                    32805
#define ID_TUM_MEDIUM                   32806
#define ID_OPTMASTER                    32807
#define ID_DLD_CREATE                   32816
#define ID_TASK_CREATE_NEW              32817
#define ID_NEED_EXIT                    32818
#define ID_SAVEALL                      32827
#define ID_MENUITEM32828                32828
#define ID__SHOWHIDEMAINWINDOW          32829
#define ID_SHOWMAINWINDOW               32829
#define ID_STARTALL                     32830
#define ID_STOPALL                      32831
#define ID_HELP_FDMWEBSITE              32832
#define ID_HOMEPAGE                     32832
#define ID_HELP_RECOMMENDTOFRIEND       32833
#define ID_RECOMMEND                    32833
#define ID_HELP_SENDEMAILTOSUPPORT      32834
#define ID_SUPPORT                      32834
#define ID_AUTOUPDATE                   32835
#define ID_UPDATE                       32836
#define ID_HOWREGISTER                  32837
#define ID_BUYONLINE                    32838
#define ID_ENTERKEY                     32839
#define ID_PROGGENERALSETTINGS          32840
#define ID_DIAL                         32841
#define ID_WHATISTHIS                   32842
#define ID_TOOLS_HANGUPWHENDONE         32843
#define ID_HANGUPWHENDONE               32843
#define ID_TOOLS_TURNOFFCOMPUTERWHENDONE 32844
#define ID_TURNOFFWHENDONE              32844
#define ID_MONITORBROWSER               32845
#define ID_MONITORCLIPBOARD             32846
#define ID_HFE_DISCONNECT               32847
#define ID_ADDSITE                      32852
#define ID_VIEW_SWBAR                   32853
#define ID_ALT1                         32854
#define ID_ALT2                         32855
#define ID_ALT3                         32856
#define ID_ALT4                         32857
#define ID_ALT5                         32858
#define ID_ALT6                         32859
#define ID_ALT7                         32860
#define ID_ALT8                         32861
#define ID_ALT9                         32862
#define ID_SPIDERDEFSETTINGS            32873
#define ID_EXPORTSETTINGS               32875
#define ID_IMPORTSETTINGS               32876
#define ID_DONTDOWNLOADANDDEL           32877
#define ID_DROPBOX                      32881
#define ID_DLD_CREATEBATCH              32900
#define ID_INSERT                       32924
#define ID_DLINFOBOX                    32925
#define ID_DLLANGFILES                  32926
#define ID_FILE_EXPORT_EXPORTLISTOFDOWNLOADS 32927
#define ID_FILE_IMPORT_IMPORTLISTOFDOWNLOADS 32928
#define ID_EXITWHENDONE                 32929
#define ID_DELETED_CLEAR                32930
#define ID_DELETED_PROPERTIES           32931
#define ID_DELETED_RESTORE              32932
#define ID_DELETED_DELETE               32933
#define ID_HISTORY_CLEAR                32934
#define ID_HISTORY_SETTINGS             32935
#define ID_FIND                         32936
#define ID_FINDNEXT                     32937
#define ID_URLTOCLIPBOARD               32938
#define ID_COPY_TO_CB                   32942
#define ID_FILE_IMPORT_IMPORTLISTOFDOWNLOADSFROMCLIPBOARD 32943
#define ID_OPTIONS_SM                   32944
#define ID_LAUNCH                       32946
#define ID_OPENFOLDER                   32947
#define ID_SPREADHELP                   32948
#define ID_HIDE                         32949
#define ID_EXPORTDLHIST                 32950
#define ID_LDF_CLEAR                    32952
#define ID_PAUSEALLDLDS                 32953
#define ID_HSTITEM_DELETE               32961
#define ID_GRPDELETEALLDEADDLDS         32963
#define ID_PORTABLE_FDM                 32982
#define ID_MENUITEM32984                32984
#define ID_DONATE                       32990
#define ID_UPLDROPTIONS                 32995
#define ID_LOADATSTARTUP                32996
#define ID_MENUITEM32998                32998
#define ID__ADDTORRENTDOWNLOADFROM      32999
#define ID_GRPSETROOTFOLDER             33000
#define ID__CREATETORRENT               33000
#define ID_BTFILES_NORMALPRIORITY       33012
#define ID_BTFILES_HIGHPIORITY          33013
#define ID_BTFILES_DONTDOWNLOAD         33014
#define ID_DLD_CREATEFLVDLD             33015
#define ID__IMPORTURLSFROMACLIPBOARD    33016
#define ID__IMPORTURLSFROMCLIPBOARD     33017
#define ID_IMPORT_IMPORT                33018
#define ID_FILE_IMPORT_MTORRENT         33019
#define ID_IMPORT_DOWNLODS_FROM_OTHER_CLIENTS 33019
#define ID_IMPORTDOWNLOADSFROMOTHERCLIENTS_ORBITDOWNLOADER 33020
#define ID_IMPORTDOWNLOADSFROMOTHERCLIENTS_LEECHGET 33021
#define ID_IMPORT_DOWNLOADSFROMOTHERCLIENTS_ORBITDOWNLOADER 33022
#define ID_IMPORT_DOWNLOADS_FROM_ORBIT  33023
#define ID_IMPORT_DOWNLOADS_FROM_LEECHGET 33024
#define ID_FILE_IMPORT_OTHER_CLIENTS_ORBIT 33025
#define ID_FILE_IMPORT_OTHER_CLIENTS_LEECHGET 33026
#define ID_FILE_IMPORT_OTHER_CLIENTS_ORBIT_DOWNLOADER 33027
#define ID_Menu                         33028
#define ID_IMPORT_IMPORTDOWNLOADSFROMOTHERCLIENTS 33029
#define ID_FILE_IMPORT_IMPORT_DOWNLOADS_FROMOTHER_MANAGERS 33030
#define ID_DOWNLOADS_CREATETPDOWNLOAD   33031
#define ID_DLD_CREATETPDOWNLOAD         33032
#define ID_SPIDERDLWEBPAGE              33900
#define ID_FDC                          34000
#define ID_PROCCEEDFURTHERINIT          34001
#define ID_SKIN_0                       35000
#define ID_SKIN_N                       35500
#define ID_LDF_0                        38000
#define IDS_COMPANY                     61204
#define ID_SB_TRAFFIC_THISDAY           61205
#define ID_SB_TRAFFIC_THISMONTH         61206
#define ID_SB_TOTALSPEED                61207

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        496
#define _APS_NEXT_COMMAND_VALUE         33236
#define _APS_NEXT_CONTROL_VALUE         1560
#define _APS_NEXT_SYMED_VALUE           137
#endif
#endif
